version: '3.4'

services:
  dotnetcoreapi-mongo: 
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./docker-compose/dotnetcoreapi-mongo/data/db:/data/db:rw
  dotnetcoreapi:
    image: ${DOCKER_REGISTRY}dotnetcoreapi
    build:
      context: .
      dockerfile: DotNetCoreApi/Dockerfile
    depends_on: 
      - dotnetcoreapi-mongo